name: Release
on:
  pull_request:
  push:
    tags:
      - "*"
jobs:
  build-n-publish:
    name: Build and publish Python ðŸ distributions ðŸ“¦
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: >
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags')) ||
      contains(toJson(github.event.pull_request.labels), 'Build wheels')
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install python-build and twine
        run: python -m pip install build twine
      - name: Build package
        run: python -m build --sdist --wheel .
      - name: List result
        run: ls -l dist
      #- name: Publish pre-release ðŸ“¦ to TestPyPI
      #  if: startsWith(github.ref, 'refs/tags') && contains(github.ref, '-')
      #  uses: pypa/gh-action-pypi-publish@release/v1
      #  with:
      #    repository-url: https://test.pypi.org/legacy/
      #    password: ${{ secrets.TEST_PYPI_TOKEN }}
      #    verbose: true
      - name: Publish pre-release ðŸ“¦ to TestPyPI
        if: startsWith(github.ref, 'refs/tags') && contains(github.ref, '-')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
        run: python -m twine upload --repository testpypi dist/*
      #- name: Publish distribution ðŸ“¦ to PyPI
      #  if: startsWith(github.ref, 'refs/tags') && !contains(github.ref, '-')
      #  uses: pypa/gh-action-pypi-publish@release/v1
      #  with:
      #    password: ${{ secrets.PYPI_TOKEN }}
      #    verbose: true
      - name: Publish distribution ðŸ“¦ to PyPI
        if: startsWith(github.ref, 'refs/tags') && !contains(github.ref, '-')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: python -m twine upload dist/*
